### PR TITLE
Fix issue #46

### PR DESCRIPTION
**Pull request by pierrecagne**
Fix for the long equal sign issue.

Solution found there : https://tex.stackexchange.com/questions/408832/replacing-tikz-cd-equal-arrow-by-custom-macro-to-work-around-grey-lines-issu

(I don't have enough expertise in pgf/tikz to see if it can be made better.)

### CODE REVIEW

**Comment by DanGrayson** [comment]
... resolves #46

**Comment by DanGrayson** [comment]
It works, but there are 5 more arrows that need to be fixed, too:
```
egrep --color=never -nH -e 'arrow.*, *equal' *.tex
group.tex:1320:\Hom(\ZZ,G) \arrow[r, equal, "\ev_{BG}"] \arrow[d, "{(f,f_0)\_}"] & 
group.tex:1322:\Hom(\ZZ,H) \arrow[r, equal, "\ev_{BH}"] & \pt_H = \pt_H \\
group.tex:1976:           &f(\pt_G) \arrow[r, equal, "f(g_0)"] & f(g(\pt_F)) \arrow[dd, equal, "p_{\pt_F}"]\\
group.tex:1977:\pt_H \arrow[ur, equal, "f_0"] \arrow[dr, equal, "f_0"']\\
group.tex:1978:           &f(\pt_G) \arrow[r, equal, "f(h_0)"]& f(h(\pt_F))\\
```

**Comment by UlrikBuchholtz** [comment]
We already have eq,eql,eqr in macros.tex right now. I think they also solve the problem. Which is preferable?

**Comment by DanGrayson** [comment]
If what we already have solves the problem it would be preferable to use those, for we avoid adding dozens of lines of code.  And if we could make the use of "equal" arrows an error, that would be good, too, so we don't fall into this trap again.

**Comment by pierrecagne** [comment]
Indeed it works with eq, did not see those tikz styles before, my mistake.

(There is a dot at the end of the definition of eq/.style that should be removed or replaced by a comma, it produces an error otherwise and I had to unquiet the makefile to determine the error. I won't make a pull request for one character though, it will wait the next one or one of your push.)

**Pull request closed without merging**
